// Sample STG Drug Data for Ghana - Offline Bootstrap
export const SAMPLE_DRUGS = [
  {
    id: 'drug-001',
    genericName: 'Amoxicillin',
    tradeName: ['Amoxil', 'Trimox'],
    strength: '500 mg',
    route: 'oral' as const,
    category: 'Antibiotic',
    stgReference: 'STG 2017 - Ch.7',
    contraindications: ['Penicillin allergy'],
    pregnancyCategory: 'A' as const,
    warnings: ['Penicillin/Cephalosporin cross-reactivity'],
  },
  {
    id: 'drug-002',
    genericName: 'Artesunate',
    tradeName: ['Arsuamoon'],
    strength: '60 mg/mL',
    route: 'iv' as const,
    category: 'Antimalarial',
    stgReference: 'STG 2017 - Ch.13',
    contraindications: [],
    pregnancyCategory: 'A' as const,
    warnings: ['First-line for severe malaria'],
  },
  {
    id: 'drug-003',
    genericName: 'Artemether',
    tradeName: ['Artem'],
    strength: '80 mg/mL',
    route: 'im' as const,
    category: 'Antimalarial',
    stgReference: 'STG 2017 - Ch.13',
    contraindications: [],
    warnings: [],
  },
  {
    id: 'drug-004',
    genericName: 'Metformin',
    tradeName: ['Glucophage'],
    strength: '500 mg',
    route: 'oral' as const,
    category: 'Antidiabetic',
    stgReference: 'STG 2017 - Ch.25',
    contraindications: ['Renal impairment (eGFR <30)'],
    pregnancyCategory: 'B' as const,
    warnings: ['Lactic acidosis risk in renal failure'],
  },
  {
    id: 'drug-005',
    genericName: 'Paracetamol',
    tradeName: ['Acetaminophen', 'Tylenol'],
    strength: '500 mg',
    route: 'oral' as const,
    category: 'Analgesic',
    stgReference: 'STG 2017 - Ch.29',
    contraindications: ['Hepatic impairment'],
    pregnancyCategory: 'A' as const,
    warnings: ['Max 4g/day to avoid hepatotoxicity'],
  },
];

export const SAMPLE_DOSE_REGIMENS = [
  {
    id: 'regimen-001-adult',
    drugId: 'drug-001',
    ageMin: 18,
    ageMax: 65,
    ageGroup: 'adult' as const,
    doseMg: '500 mg',
    frequency: 'Every 8 hours',
    duration: '7 days',
    maxDoseMgDay: '3000 mg',
    route: 'oral',
    instructions: 'Take with or without food',
  },
  {
    id: 'regimen-001-peds',
    drugId: 'drug-001',
    ageMin: 2,
    ageMax: 17,
    weightMin: 10,
    weightMax: 50,
    ageGroup: 'pediatric' as const,
    doseMg: '25 mg/kg',
    frequency: 'Every 8 hours',
    duration: '7 days',
    route: 'oral',
    instructions: 'Divide total daily dose into 3 doses',
  },
  {
    id: 'regimen-002-adult',
    drugId: 'drug-002',
    ageMin: 18,
    ageGroup: 'adult' as const,
    doseMg: '2.4 mg/kg',
    frequency: 'Once daily',
    duration: 'Until parasite clearance',
    route: 'iv',
    instructions: 'Slow IV infusion over 2-3 minutes',
  },
  {
    id: 'regimen-002-peds',
    drugId: 'drug-002',
    ageMin: 2,
    ageMax: 17,
    weightMin: 10,
    weightMax: 50,
    ageGroup: 'pediatric' as const,
    doseMg: '3.2 mg/kg',
    frequency: 'Once daily',
    duration: 'Until parasite clearance',
    route: 'iv',
    instructions: 'Slow IV infusion over 2-3 minutes',
  },
  {
    id: 'regimen-003-adult',
    drugId: 'drug-003',
    ageMin: 18,
    weightMin: 40,
    ageGroup: 'adult' as const,
    doseMg: '160 mg',
    frequency: 'Once daily',
    duration: 'Until parasite clearance',
    route: 'im',
    instructions: 'Deep intramuscular injection',
  },
  {
    id: 'regimen-003-peds',
    drugId: 'drug-003',
    ageMin: 2,
    ageMax: 17,
    weightMin: 10,
    weightMax: 50,
    ageGroup: 'pediatric' as const,
    doseMg: '3.2 mg/kg',
    frequency: 'Once daily',
    duration: 'Until parasite clearance',
    route: 'im',
    instructions: 'Deep intramuscular injection',
  },
  {
    id: 'regimen-004-adult',
    drugId: 'drug-004',
    ageMin: 18,
    ageGroup: 'adult' as const,
    doseMg: '500 mg',
    frequency: 'Twice to three times daily',
    duration: 'Chronic',
    maxDoseMgDay: '2550 mg',
    route: 'oral',
    instructions: 'Take with meals to reduce GI upset',
  },
  {
    id: 'regimen-004-peds',
    drugId: 'drug-004',
    ageMin: 10,
    ageMax: 17,
    weightMin: 30,
    weightMax: 70,
    ageGroup: 'pediatric' as const,
    doseMg: '500 mg',
    frequency: 'Once or twice daily',
    duration: 'Chronic',
    maxDoseMgDay: '1500 mg',
    route: 'oral',
    instructions: 'Take with meals to reduce GI upset. Not recommended under 10 years',
  },
  {
    id: 'regimen-005-adult',
    drugId: 'drug-005',
    ageMin: 18,
    ageGroup: 'adult' as const,
    doseMg: '500-1000 mg',
    frequency: 'Every 4-6 hours',
    duration: 'As needed',
    maxDoseMgDay: '4000 mg',
    route: 'oral',
    instructions: 'Do not exceed 4g daily',
  },
  {
    id: 'regimen-005-peds',
    drugId: 'drug-005',
    ageMin: 2,
    ageMax: 17,
    weightMin: 10,
    weightMax: 50,
    ageGroup: 'pediatric' as const,
    doseMg: '15 mg/kg',
    frequency: 'Every 4-6 hours',
    duration: 'As needed',
    maxDoseMgDay: '5 doses/day',
    route: 'oral',
    instructions: 'Dosage based on weight, not to exceed 5 doses daily',
  },
];
