-- Create DispensingEvent table if missing (guarded)

CREATE TABLE IF NOT EXISTS "DispensingEvent" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dispenseRecordId" text,
  timestamp timestamp with time zone NOT NULL,
  "pharmacyId" text,
  "userId" integer,
  "drugId" text NOT NULL,
  "drugName" text,
  "genericName" text,
  "patientAgeGroup" text,
  "isPrescription" boolean NOT NULL DEFAULT true,
  "isControlledDrug" boolean NOT NULL DEFAULT false,
  "isAntibiotic" boolean NOT NULL DEFAULT false,
  "stgCompliant" boolean NOT NULL DEFAULT false,
  "overrideFlag" boolean NOT NULL DEFAULT false,
  "overrideReason" text,
  "patientIsPregnant" boolean NOT NULL DEFAULT false,
  "riskScore" double precision,
  "riskCategory" text,
  "riskFlags" text,
  "highRiskFlag" boolean NOT NULL DEFAULT false,
  "printDurationSec" integer,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now()
);

-- Indexes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='DispensingEvent' AND indexname='DispensingEvent_timestamp_idx') THEN
    CREATE INDEX "DispensingEvent_timestamp_idx" ON "DispensingEvent"("timestamp");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='DispensingEvent' AND indexname='DispensingEvent_pharmacyId_idx') THEN
    CREATE INDEX "DispensingEvent_pharmacyId_idx" ON "DispensingEvent"("pharmacyId");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='DispensingEvent' AND indexname='DispensingEvent_drugId_idx') THEN
    CREATE INDEX "DispensingEvent_drugId_idx" ON "DispensingEvent"("drugId");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='DispensingEvent' AND indexname='DispensingEvent_riskCategory_idx') THEN
    CREATE INDEX "DispensingEvent_riskCategory_idx" ON "DispensingEvent"("riskCategory");
  END IF;
END $$;

-- Optional sample seed row if table empty (keeps timestamps deterministic)
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM "DispensingEvent") = 0 THEN
    INSERT INTO "DispensingEvent" ("timestamp", "pharmacyId", "drugId", "drugName", "genericName")
    VALUES (now(), 'ALL_PHARMACIES', 'DRUG-EXAMPLE-1', 'ExampleDrug', 'ExampleGeneric');
  END IF;
END $$;
