-- Create Pharmacy table if missing, seed sample rows, then add FK constraints

CREATE TABLE IF NOT EXISTS "Pharmacy" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  location text,
  address text,
  phone text,
  email text,
  "licenseNumber" text,
  manager text,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='Pharmacy' AND indexname='Pharmacy_name_idx') THEN
    CREATE INDEX "Pharmacy_name_idx" ON "Pharmacy"(name);
  END IF;
END $$;

-- Seed sample pharmacies only if table is empty
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM "Pharmacy") = 0 THEN
    INSERT INTO "Pharmacy" (name, location, address, phone, email, "licenseNumber", manager)
    VALUES
      ('Central Pharmacy', 'Main', '123 Main St', '+1-555-0001', 'central@example.com', 'LIC-0001', 'Alice Manager'),
      ('North Clinic Pharmacy', 'North', '456 North Ave', '+1-555-0002', 'north@example.com', 'LIC-0002', 'Bob Manager');
  END IF;
END $$;

-- Add FK constraints for integer pharmacyId columns where appropriate
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='User' AND table_schema='public') AND
     EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='User' AND column_name='pharmacyId') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='User_pharmacyId_fkey') THEN
      ALTER TABLE "User" ADD CONSTRAINT "User_pharmacyId_fkey" FOREIGN KEY ("pharmacyId") REFERENCES "Pharmacy"(id) ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;
  END IF;

  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='DispenseRecord' AND table_schema='public') AND
     EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='DispenseRecord' AND column_name='pharmacyId') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='DispenseRecord_pharmacyId_fkey') THEN
      ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_pharmacyId_fkey" FOREIGN KEY ("pharmacyId") REFERENCES "Pharmacy"(id) ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;
  END IF;
END $$;
