-- Create HighRiskAlert table if missing (guarded)

CREATE TABLE IF NOT EXISTS "HighRiskAlert" (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "dispensingEventId" integer,
  "timestamp" timestamp with time zone NOT NULL DEFAULT now(),
  "pharmacyId" text,
  "userId" integer,
  "drugId" text NOT NULL,
  "riskScore" double precision,
  "riskCategory" text,
  "riskFlags" text,
  message text,
  acknowledged boolean NOT NULL DEFAULT false,
  "acknowledgedBy" integer,
  "acknowledgedAt" timestamp with time zone,
  "createdAt" timestamp with time zone NOT NULL DEFAULT now(),
  "updatedAt" timestamp with time zone NOT NULL DEFAULT now()
);

-- Indexes
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='HighRiskAlert' AND indexname='HighRiskAlert_pharmacyId_idx') THEN
    CREATE INDEX "HighRiskAlert_pharmacyId_idx" ON "HighRiskAlert"("pharmacyId");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='HighRiskAlert' AND indexname='HighRiskAlert_timestamp_idx') THEN
    CREATE INDEX "HighRiskAlert_timestamp_idx" ON "HighRiskAlert"("timestamp");
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE tablename='HighRiskAlert' AND indexname='HighRiskAlert_riskCategory_idx') THEN
    CREATE INDEX "HighRiskAlert_riskCategory_idx" ON "HighRiskAlert"("riskCategory");
  END IF;
END $$;

-- Optional seed row if empty
DO $$
BEGIN
  IF (SELECT COUNT(*) FROM "HighRiskAlert") = 0 THEN
    INSERT INTO "HighRiskAlert" ("dispensingEventId", "pharmacyId", "drugId", "riskScore", "riskCategory", message)
    VALUES (NULL, 'ALL_PHARMACIES', 'DRUG-EXAMPLE-1', 0.0, 'low', 'Seed alert');
  END IF;
END $$;

-- Optional FK to DispensingEvent if exists
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name='DispensingEvent' AND table_schema='public') THEN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='HighRiskAlert_dispensingEventId_fkey') THEN
      ALTER TABLE "HighRiskAlert" ADD CONSTRAINT "HighRiskAlert_dispensingEventId_fkey" FOREIGN KEY ("dispensingEventId") REFERENCES "DispensingEvent"(id) ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
  END IF;
END $$;
